### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by makaay2077** [Amsterdam-AI-Team/Geolocalization#1]
I congratulate you for this beautiful work.

I get an error when I run the "python -m examples.visualize_intersections -c "data/faster_r-cnn_output/bicycle_symbols_example.csv"" codes. 

Traceback (most recent call last):
  File "C:\Users\123gu\anaconda3\envs\open3d\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\123gu\anaconda3\envs\open3d\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\123gu\Desktop\dosyalar\Geolocalization_of_Street_Objects-master\examples\visualize_intersections.py", line 84, in <module>
    initial_location = get_pano_location(pano_id)
  File "C:\Users\123gu\Desktop\dosyalar\Geolocalization_of_Street_Objects-master\src\api_request.py", line 16, in get_pano_location
    pano_data = json.loads(response.content)
  File "C:\Users\123gu\anaconda3\envs\open3d\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\123gu\anaconda3\envs\open3d\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\123gu\anaconda3\envs\open3d\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Can you help?

**Comment by chrise96** [comment]
Hi makaay2077,  
Thank you! The City of Amsterdam paused the public access of [https://api.data.amsterdam.nl/panorama/panoramas/](https://api.data.amsterdam.nl/panorama/panoramas/). It will be back online in a few weeks hopefully 👍
